name = "tackmore-dashboard-api"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "tackmore-dashboard"
database_id = "d59a3b1d-f159-4e23-9136-304c09842745"

[triggers]
crons = [
  "0 0 1 * *",
  "0 0 * * *"
]
